export { default as Backo } from "./Backo";
export { default as Carrillo } from "./Carrillo";
export { default as Eye } from "./Eye";
export { default as Notificazion } from "./Notificazion";
export { default as Search } from "./Search";
export { default as Traile } from "./Traile";
export { default as Tren } from "./Tren";
export { default as Ubi } from "./Ubi";
export { default as User } from "./User";
